version: "3"
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/data:/var/lib/mysql
  redis:
    image: "redis:6.0.12"
    ports:
      - "6379:6379"
    # volumes:
      # - "./redis/data/redis:/data"
  go-app:
    image: golang:latest
    tty: true
    # restart: always
    environment:
      APP_DBHOST: db
      APP_DBPORT: 3306
    ports: 
      - "8081:3000"
    depends_on: ["db","redis"]
    volumes:
      - ./app:/home/app
    working_dir: /home
    command: bash -c "cd app && go run cmd/main.go"
  frontapp:
    build: ./frontapp
    ports: ["8080:8080"]
    volumes:
      - ./frontapp:/home/ui
    command: "npm run serve"
