openapi: 3.0.0
info:
  title: Picture application APIs
  description: フロントエンドがアクセスするAPI群を定義する.
  version: 1.0.0
  license:
      name: swagger
      url: https://swagger.io/docs/specification/about/

servers:
  - url: http://localhost:3000/
    description: development server

paths:
  /v1/employees:
    get:
      tags:
        - management
      summary: get all employees
      description: get all employees informations
      parameters: []
      responses:
        '200':
          description: a json array of employees informations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
                example:
                   - name: taro tanaka
                     data: AGDKS+FOIEDFESAFEILDIE
                     updateDateTime: 2020/10/03 18:27:30
                     department: development
                     remarks: ""
    post:
      tags:
        - admin
      summary: create a employee data
      description: create a employee data
      parameters: []
      requestBody:
        description: employee to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
            example:
              - name: taro tanaka
                data: AGDKS+FOIEDFESAFEILDIE
                updateDateTime: 2020/10/03 18:27:30
                department: development
                remarks: ""
      responses:
        '201':
          description: CREATED
  /v1/auth/login/:
    post:
      tags:
        - admin
      summary: login
      description: login
      parameters: []
      requestBody:
        description: user to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              userID: tanaka
              password: "1234"
      responses:
        '200':
          description: OK
        '401':
          description: Login FOIEDFESAFEILDIE
components:
  schemas: 
    Employee:
      type: object
      properties:
          name:
            type: string
          data:
            type: string
            format: byte # base64 encorded
          department:
            type: string
          updateDateTime:
            type: string
            format: date-time
          remarks:
            type: string
    User:
      type: object
      properties:
          userID:
            type: string
          name:
            type: string
          password:
            type: string
tags:
  - name: management
    description: apis for management
externalDocs:
    description: Swagger(openapi)記法の参考記事
    url: https://qiita.com/teinen_qiita/items/e440ca7b1b52ec918f1b#tags
