// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entities

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Employees", testEmployeesUpsert)

	t.Run("Users", testUsersUpsert)
}
