use mydb;

-- Employee
CREATE TABLE employee (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    picture BLOB NOT NULL,
    update_date_time TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    department VARCHAR(50),
    remarks VARCHAR(200),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id)
);

-- user
CREATE TABLE user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id)
);

